---
- hosts: dev
  become: yes

  tasks:

    - name: Install Apache
      dnf:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create webdev directory
      file:
        path: /webdev
        state: directory

    - name: Create index page
      copy:
        content: "development\n"
        dest: /webdev/index.html

    - name: Remove default html directory
      file:
        path: /var/www/html
        state: absent

    - name: Create symbolic link
      file:
        src: /webdev
        dest: /var/www/html
        state: link
