---
- hosts: dev
  become: yes

  tasks:
    - name: Set issue file for dev group
      copy:
        content: "development\n"
        dest: /etc/issue

- hosts: test
  become: yes

  tasks:
    - name: Set issue file for test group
      copy:
        content: "test\n"
        dest: /etc/issue
